// components/icons/index.tsx
import {
  IconActivity,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertOctagon,
  IconAlertTriangle,
  IconArrowDown,
  IconArrowDownRight,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUpRight,
  IconArrowsShuffle,
  IconArrowsUpDown,
  IconBell,
  IconBike,
  IconBolt,
  IconBox,
  IconBuilding,
  IconBuildingStore,
  IconCalendar,
  IconCashBanknote,
  IconChartBar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsUp,
  IconCircle,
  IconCircleCheck,
  IconCircleX,
  IconClipboardList,
  IconClock,
  IconCompass,
  IconCopy,
  IconCreditCard,
  IconCrosshair,
  IconCurrencyDollar,
  IconCurrentLocation,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDeviceMobile,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconDumbbell,
  IconEdit,
  IconEye,
  IconEyeOff,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFlame,
  IconGift,
  IconGlobe,
  IconGripVertical,
  IconHandStop,
  IconHash,
  IconHeart,
  IconHelp,
  IconHome,
  IconInfoCircle,
  IconKey,
  IconLayersIntersect,
  IconLayout,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconLayoutList,
  IconLayoutSidebarLeftCollapse,
  IconLoader2,
  IconLogout,
  IconMail,
  IconMap,
  IconMapPin,
  IconMaximize,
  IconMessage2,
  IconMessageCircle,
  IconMinimize,
  IconMinus,
  IconMoon,
  IconNavigation,
  IconPackage,
  IconPalette,
  IconPaperclip,
  IconPercentage,
  IconPhone,
  IconPhoto,
  IconPill,
  IconPlayerPlay,
  IconPlus,
  IconPointer,
  IconPower,
  IconPuzzle,
  IconRadio,
  IconRefresh,
  IconRotateDot,
  IconRoute,
  IconRss,
  IconSatellite,
  IconSearch,
  IconSend,
  IconServer,
  IconSettings,
  IconShare2,
  IconShield,
  IconShieldCheck,
  IconShoppingBag,
  IconShoppingCart,
  IconSparkles,
  IconSpeakerphone,
  IconStar,
  IconSun,
  IconTag,
  IconTarget,
  IconToggleLeft,
  IconToggleRight,
  IconTool,
  IconTools,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTruck,
  IconTypography,
  IconUser,
  IconUserCheck,
  IconUserX,
  IconUsers,
  IconVolume,
  IconWallet,
  IconWifi,
  IconX,
} from '@tabler/icons-react';

export {
  IconActivity as Activity,
  IconAlertCircle as AlertCircle,
  IconAlertOctagon as AlertOctagon,
  IconAlertTriangle as AlertTriangle,
  IconArrowDown as ArrowDown,
  IconArrowDownRight as ArrowDownRight,
  IconArrowLeft as ArrowLeft,
  IconArrowRight as ArrowRight,
  IconArrowsUpDown as ArrowUpDown,
  IconArrowUpRight as ArrowUpRight,
  IconCashBanknote as Banknote,
  IconChartBar as BarChart3,
  IconBell as Bell,
  IconBike as Bike,
  IconBox as Box,
  IconBuilding as Building,
  IconCalendar as Calendar,
  IconCheck as Check,
  IconChecks as CheckCheck,
  IconCircleCheck as CheckCircle,
  IconCircleCheck as CheckCircle2,
  IconCheck as CheckIcon,
  IconChevronDown as ChevronDown,
  IconChevronDown as ChevronDownIcon,
  IconChevronLeft as ChevronLeft,
  IconChevronLeft as ChevronLeftIcon,
  IconChevronRight as ChevronRight,
  IconChevronRight as ChevronRightIcon,
  IconChevronUp as ChevronUp,
  IconChevronUp as ChevronUpIcon,
  IconChevronsUp as ChevronsUp,
  IconCircle as Circle,
  IconCircle as CircleIcon,
  IconClipboardList as ClipboardList,
  IconClock as Clock,
  IconCompass as Compass,
  IconCopy as Copy,
  IconCreditCard as CreditCard,
  IconCrosshair as Crosshair,
  IconDatabase as Database,
  IconCurrencyDollar as DollarSign,
  IconDownload as Download,
  IconDumbbell as Dumbbell,
  IconEdit as Edit2,
  IconEdit as Edit3,
  IconEye as Eye,
  IconEyeOff as EyeOff,
  IconDownload as FileDown,
  IconFileText as FileText,
  IconFilter as Filter,
  IconFlag as Flag,
  IconFlame as Flame,
  IconGift as Gift,
  IconGlobe as Globe,
  IconGripVertical as GripVerticalIcon,
  IconHandStop as Hand,
  IconServer as HardDrive,
  IconHash as Hash,
  IconHeart as Heart,
  IconHelp as HelpCircle,
  IconHome as Home,
  IconPhoto as Image,
  IconPhoto as ImageIcon,
  IconInfoCircle as Info,
  IconKey as Key,
  IconLayersIntersect as Layers,
  IconLayout as Layout,
  IconLayoutDashboard as LayoutDashboard,
  IconLayoutGrid as LayoutGrid,
  IconLayoutList as LayoutList,
  IconLoader2 as Loader2,
  IconCurrentLocation as Locate,
  IconLogout as LogOut,
  IconMail as Mail,
  IconMap as Map,
  IconMapPin as MapPin,
  IconMaximize as Maximize,
  IconMaximize as Maximize2,
  IconSpeakerphone as Megaphone,
  IconMessageCircle as MessageCircle,
  IconMessage2 as MessageSquare,
  IconMinimize as Minimize2,
  IconMinus as Minus,
  IconMinus as MinusIcon,
  IconDeviceDesktop as Monitor,
  IconMoon as Moon,
  IconDots as MoreHorizontal,
  IconDots as MoreHorizontalIcon,
  IconDotsVertical as MoreVertical,
  IconPointer as MousePointer,
  IconNavigation as Navigation,
  IconPackage as Package,
  IconPackage as PackagePlus,
  IconPalette as Palette,
  IconLayoutSidebarLeftCollapse as PanelLeftIcon,
  IconPaperclip as Paperclip,
  IconPercentage as Percent,
  IconPhone as Phone,
  IconPill as Pill,
  IconPlayerPlay as Play,
  IconPlus as Plus,
  IconPower as Power,
  IconPuzzle as Puzzle,
  IconRadio as Radio,
  IconRefresh as RefreshCw,
  IconRotateDot as RotateCcw,
  IconRoute as Route,
  IconRss as Rss,
  IconSatellite as Satellite,
  IconDeviceFloppy as Save,
  IconSearch as Search,
  IconSearch as SearchIcon,
  IconSend as Send,
  IconSettings as Settings,
  IconShare2 as Share2,
  IconShield as Shield,
  IconShieldCheck as ShieldCheck,
  IconShoppingBag as ShoppingBag,
  IconShoppingCart as ShoppingCart,
  IconArrowsShuffle as Shuffle,
  IconAdjustmentsHorizontal as SlidersHorizontal,
  IconDeviceMobile as Smartphone,
  IconSparkles as Sparkles,
  IconStar as Star,
  IconBuildingStore as Store,
  IconSun as Sun,
  IconTag as Tag,
  IconTarget as Target,
  IconClock as Timer,
  IconToggleLeft as ToggleLeft,
  IconToggleRight as ToggleRight,
  IconTrash as Trash2,
  IconTrendingDown as TrendingDown,
  IconTrendingUp as TrendingUp,
  IconTruck as Truck,
  IconTypography as Type,
  IconUser as User,
  IconUserCheck as UserCheck,
  IconUserX as UserX,
  IconUsers as Users,
  IconTools as Utensils,
  IconDeviceMobile as Vibrate,
  IconVolume as Volume2,
  IconWallet as Wallet,
  IconWifi as Wifi,
  IconTool as Wrench,
  IconX as X,
  IconCircleX as XCircle,
  IconX as XIcon,
  IconBolt as Zap,
};
